# Add fix3
_build: &_build
  language: node_js
  node_js: "lts/*"

  cache:
    - yarn

  git:
    submodules: false

  #before_install:
    #- sed -i "s/git@github.com:/https:\/\/x-access-token:${GITHUB_ACCESS_TOKEN}@github.com\//g" .gitmodules
    #- git submodule update --init --recursive
    #- yarn

  install:
    - echo "install"

  script:
    #- yarn lint
    #- yarn build:$BUILD_ENV
    #- yarn test:unit
    ## - yarn test:e2e --headless
    - env |sort

_env-lab: &_env-lab
  env:
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - AWS_ACCESS_KEY_ID=${DEV_AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${DEV_AWS_SECRET_ACCESS_KEY}
    - BUILD_ENV=${DEV_BUILD_ENV}
    - S3_TARGET_BUCKET=${DEV_S3_TARGET_BUCKET}

_env-staging: &_env-staging
  env:
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - AWS_ACCESS_KEY_ID=${STAGING_AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${STAGING_AWS_SECRET_ACCESS_KEY}
    - BUILD_ENV=${STAGING_BUILD_ENV}
    - S3_TARGET_BUCKET=${STAGING_S3_TARGET_BUCKET}

_env-production: &_env-production
  env:
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - AWS_ACCESS_KEY_ID=${PRODUCTION_AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${PRODUCTION_AWS_SECRET_ACCESS_KEY}
    - BUILD_ENV=${PRODUCTION_BUILD_ENV}
    - S3_TARGET_BUCKET=${PRODUCTION_S3_TARGET_BUCKET}

_s3deployment: &_s3deployment
  #provider: s3
  #region: ${AWS_DEFAULT_REGION}
  #access_key_id: ${AWS_ACCESS_KEY_ID}
  #secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  #bucket: ${S3_TARGET_BUCKET}
  #cleanup: false
  #local_dir: dist
  #upload-dir: vip25d
  provider: script
  script: env |sort

_before_deploy_tag_files: &_before_deploy_tag_files
  before_deploy:
    - make copy-file-with-tag

stages:
  # Default build
  - name: build-test

  # Condition stage
  - name: tag-deployment-lab
    if: tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)-beta$/ 

  - name: tag-deployment-staging
    if: tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)-rc$/

  - name: tag-deployment-production-
    if: tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)$/

  - name: branch-deployment-lab
    if: branch = lab

  - name: branch-deployment-staging
    if: branch = staging

  - name: branch-deployment-production
    if: branch = production

jobs:
  include:

    - stage: build-test
      name: Build
      <<: *_build

    # Tag deployment
    - stage: tag-deployment-lab
      name: Deployment
      <<: *_env-lab
      <<: *_build
      <<: *_before_deploy_tag_files
      deploy:
        <<: *_s3deployment
        on:
          tags: true

    # Branch deployment
    - stage: branch-deployment-lab
      name: Deployment
      <<: *_env-lab
      <<: *_build
      deploy:
        <<: *_s3deployment
        
notifications:
  email:
    on_success: never
  slack:
    on_success: never
    rooms:
      secure: 104corp:U3sSJiAnHfM5Da3cthMtaoDo
