sudo: true

before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.7
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
  - virtualenv -p /usr/bin/python3 py3env
  - source py3env/bin/activate
  - python -V 
  - pip -V
  - pip install awscli

script:
  - echo ok
