dist: xenial
script:
  - echo "Global build"
  - env

stages:
  - name: test
  - name: deployment-tag-master
    if: tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)-beta$/

jobs:
  include:

    - stage: test
      name: Global Test
      script: echo "Global test"
    - name: Global Test env
      script: env

    - stage: deployment-tag-master
      name: deployment
      script: echo "master deployment" && env
