sudo: required
language: go

dist: xenial
go:
  - 1.11.x
services:
  - docker

script:
  - echo "hello"
  - pip install --user jq
  - echo '[{"aaa":"bbb"}]' |jq
  - jq --help
  - which jq
  - echo $PATH
  - find . -type f
