dist: xenial
#before_install:
#  - bash test.sh
#install:
#  - bash test.sh
script:
  - bash test.sh
before_deploy:
  - bash test.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ${TRAVIS_BUILD_DIR}/test.sh
