dist: xenial
script:
  - echo "Global build"
  - env

stages:
  - name: test
  - name: deployment-tag-master

jobs:
  include:

    - stage: test
      name: Stage Test
      script: echo "Global test"
    - name: Stage Test env
      script: env

    - stage: deployment-tag-master
      name: Do master tag deployment
      script: echo "master deployment" && env && echo ${TRAVIS_TAG}
      if: tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)-beta$/