sudo: required

language: python

dist: xenial

services:
  - docker

script:
  - echo $(SLACK_CHANNEL)
  - aws
  - if [[ 1=1 ]]; then
      echo 1;
      echo 2;
    fi

notifications:
  email: false
  slack: $(SLACK_CHANNEL)