dist: xenial
#before_install:
#  - bash test.sh
#install:
#  - bash test.sh
script:
  - env

stages:
  - name: deployment-tag-master
    if: (tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)-beta$/) AND (branch = master)


jobs:
  include:
    - stage: deployment-tag-master
      script: env