dist: xenial
#before_install:
#  - bash test.sh
#install:
#  - bash test.sh
script:
  - pip install awscli --user
  - echo ${TRAVIS_COMMIT}
before_deploy:
  - export AWS_ACCESS_KEY_ID=123456
  - export AWS_SECRET_ACCESS_KEY=123456
  - export AWS_SESSION_TOKEN=123456


stages:
  - name: tag-deployment-lab
    if: (tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)-beta$/) AND (branch = lab)

  - name: tag-deployment-staging
    if: (tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)-rc$/) AND (branch = staging)

  - name: tag-deployment-production
    if: (tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)$/) AND (branch = production)


jobs:
  include:
    - stage: tag-deployment-lab
      name: tag-deployment-lab
      script: env
    include:
    - stage: tag-deployment-staging
      name: tag-deployment-staging
      script: env
    include:
    - stage: tag-deployment-production
      name: tag-deployment-production
      script: env



