dist: xenial
script:
  - env

stages:
  - name: deployment-tag-master
    #if: (tag =~ /^(v|V)([0-9]*)\.([0-9]*)\.([0-9]*)-beta$/) AND (branch = master)
    if: branch = master

jobs:
  include:
    - stage: deployment-tag-master
      script: env