dist: xenial
#before_install:
#  - bash test.sh
#install:
#  - bash test.sh
script:
  - pip install awscli --user
  - echo ${TRAVIS_COMMIT}
before_deploy:
  - export AWS_ACCESS_KEY_ID=123456
  - export AWS_SECRET_ACCESS_KEY=123456
  - export AWS_SESSION_TOKEN=123456
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ${TRAVIS_BUILD_DIR}/test.sh
